name: SDCT-776 Scenario 2 - Multiple Test Failures in Single Job

on:
  push:
    branches:
      - dani.fernandez/sdct776-scenario2-multi-tests

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_SITE: datad0g.com
      DD_CIVISIBILITY_AGENTLESS_ENABLED: true
      DD_SERVICE: sdct776-pr-signals
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Run 3 test failures
        run: go test -tags=sdct776 -run '^TestRetryPolicy' -v ./sdct776/scenarios
