name: Test PR Signals Links In Error Messages

on:
  push:
    branches:
      - dani.fernandez/test-object-is-links
  pull_request:

jobs:
  unit-test-packages:
    name: unit-test-packages
    runs-on: ubuntu-latest
    env:
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DD_SITE: datad0g.com
      DD_CIVISIBILITY_AGENTLESS_ENABLED: true
      DD_SERVICE: sdct776-pr-signals
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Run test
        run: |
          go test -tags=sdct776 -v ./sdct776/scenarios -run '^TestObjectIsEquality$'
